language: python
python:
    - 2.6
    - 2.7
env:
  - TOX_ENV=dj14
  - TOX_ENV=dj15
  - TOX_ENV=cms23
  - TOX_ENV=cms24_14
  - TOX_ENV=cms24_15

install:
    - pip install tox --use-mirrors
script:
    tox -e $TOX_ENV
notifications:
    email:
        recipients:
          - github@spalletti.it
        on_success: never
        on_failure: always

matrix:
  exclude:
    - python: 2.6